# default - Default attribute values for the pack

default['spark-v1']['spark_custom_download'] = '$OO_LOCAL{nexus}'
default['spark-v1']['hadoop_dir'] = '/opt/hadoop'
default['spark-v1']['hadoop_dir'] = '/opt/hadoop'
default['spark-v1']['hive_dir'] = '/opt/hive'
default['spark-v1']['spark_base'] = '/opt'
default['spark-v1']['spark_tmp_dir'] = '/work'
default['spark-v1']['spark_version'] = ' '
default['spark-v1']['spark_master'] = ''
default['spark-v1']['worker_cores'] = '2'
default['spark-v1']['worker_memory'] = '2g'
default['spark-v1']['master_opts'] = '[]'
default['spark-v1']['worker_opts'] = '[]'
default['spark-v1']['spark_config'] = '{}'
default['spark-v1']['enable_ganglia'] = 'false'
default['spark-v1']['ganglia_servers'] = ''
default['spark-v1']['enable_thriftserver'] = 'false'
default['spark-v1']['thrift_server_port'] = '10000'
default['spark-v1']['thrift_ldap_server'] = ''
default['spark-v1']['thrift_ldap_domain'] = ''
default['spark-v1']['is_client_only'] = 'false'
default['spark-v1']['enable_historyserver'] = 'true'
default['spark-v1']['spark_events_dir'] = '/work/events'
default['spark-v1']['history_server_port'] = '18080'
default['spark-v1']['use_yarn'] = 'false'
